### ISSUE TITLE
Update Examples

### ISSUE THREAD

**Issue by jelaw21** [tmetcalfe89/interactions#12]
The example script on the README for using particleType uses iconcrack. I think it needs to be updated to include a parameter?

Thanks.

**Comment by tmetcalfe89-zz** [comment]
That used to be the case. As of 1.7(.1), it is now optional, and defaults to the target block as the parameter. In the case of that example, leaving it as just `iconcrack` is the equivalent of `iconcrack:minecraft:diamond_ore:0`, since the `targetBlock` is `minecraft:diamond_ore`.
