### ISSUE TITLE
[Feature Request ???] dropItem function drops the item at the ~0,~0,~0 coordinate of the block, leading to odd item entity behaviour

### ISSUE THREAD

**Issue by TeetoKaziim** [tmetcalfe89/interactions#17]
The default location where the items are dropped into the world is at the bottom-north-west corner of the block. In the case of blocks on the ground, this results in the item entity spawning in the ground, and zipping oddly about (as item entities trapped inside blocks do). If this is on a platform over a drop, the items fall rather than end up anywhere the player can collect them. This is admittedly, in most cases, a very minor quibble, but, a few ideas popped into my head as to ways this could be addressed. So I'm sharing them. Feel free to use/ignore them at your leisure.

1) Have an optional set of parameters where the packmaker can define where the item will be spawned relative to the block being clicked on. Such as:
```
"dropXYZ": "float:float:float"
```
So, if the packmaker wanted to spawn the item in the middle of the top of the block, they could put `"0.5:1.1:0.5"`

2) Have the item spawn at the location-on-the-block that the player clicked. If not the exact spot, perhaps the center of the face they clicked on? I do not know if the necessary information is sent to the server to actually do this. But I'm mentioning it. Upsides, the item is generally never going to be "inside of blocks" when spawned.

3) A new set of "giveItem" parameters that instead of spawning an item entity, just give it to the player doing the interaction directly: `"giveItem"`, `"giveOnlyOnSuccess"`, `"giveChance"`, `"giveCount"`. This one could be a fully independent feature request, I only mention it here because this behaviour I'm whining about is what made me think of it.

4) Have a different default drop location for the item entities. This is probably the easiest, and the worst, because, much like how `0,0,0` doesn't cover all use cases, no other combination of coordinates will either.

Thank you for your time and consideration.

**Comment by tmetcalfe89-zz** [comment]
Implemented suggestion 2. Will probably implement suggestion 3 separately; have an idea for that.

**Comment by TeetoKaziim** [comment]
The new behaviour is slick and stylin, feels noticably better.

Thanks so much :3
