### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jelaw21** [tmetcalfe89/interactions#2]
[crash-2019-09-16_20.03.35-client.txt](https://github.com/tmetcalfe89/interactions/files/3618654/crash-2019-09-16_20.03.35-client.txt)

**Comment by tmetcalfe89-zz** [comment]
Leaving work now. Can you post the JSON as well, please?

**Comment by jelaw21** [comment]
I already changed it, let me see if I can replicate.

**Comment by jelaw21** [comment]
https://pastebin.com/cwWx5qqU

Its the blockdust particle

**Comment by jelaw21** [comment]
blockcrack as well

**Comment by tmetcalfe89-zz** [comment]
That makes sense. They probably need a block to reference. Does it work with happyVillager? I know that works for sure.

**Comment by jelaw21** [comment]
Oh it works with A BUNCH of them ... but those are the ones that don't so
far.  Its GREAT!!  My pack is coming to life!

**Comment by tmetcalfe89-zz** [comment]
Awesome! Glad to hear it :)

**Comment by jelaw21** [comment]
![interactionsDemo](https://user-images.githubusercontent.com/21100827/65002780-6074cb00-d8c3-11e9-8499-61700e352dc2.gif)
 I don't mind if you use this gif, but I would ask to wait until after I've released my pack.

**Comment by tmetcalfe89-zz** [comment]
I would love to see the pack when it's complete!

**Comment by jelaw21** [comment]
I have released the pack. Its playable in single player, but has some issues in Multiple player. Feel free to use the gif above if you want to.   The pack is called Skyblock Billionaire.

**Comment by tmetcalfe89-zz** [comment]
I'd like to help on the issues, if I could. Were they from my mod? Feel free to PM me if not and I'll see what I can do!

**Comment by jelaw21** [comment]
I've "fixed" two of the issues. One was with the soulus mod which should be
sorted on their next update. The other is with EnderIO vs. Twitch, but I'll
just roll back to a previous version. However, because of the amount of
scripts, I believe, server/client keeps timing out and cannot connect, even
when increasing the timeout time.

**Comment by jelaw21** [comment]
I've fixed the server issues. It should be up soon.  Waiting for FTB to fix
an issue with their Teams GUI and I'll be all set to open.
