### ISSUE TITLE
[Feature Request] Consume item

### ISSUE THREAD

**Issue by Foreck1** [tmetcalfe89/interactions#20]
Please forgive me if this is already possible and I didn't notice, there's already a function to damage an IItemStack, but one to get rid of the held item would allow for consumables, a much needed extra for some more advanced interactions.

**Comment by Foreck1** [comment]
Nevermind, it "damages" stacks too and I just failed to understand the last note in the wiki at all, sorry about it 😔

**Comment by tmetcalfe89-zz** [comment]
Give `damage` a shot!

It should process as:
If held item can be damaged, damage it by that amount.
If held item cannot be damaged, take that amount out of the stack.

Hah, you got to it before I did...
