### ISSUE TITLE
[Feature Request] Multiple Drops

### ISSUE THREAD

**Issue by jelaw21** [tmetcalfe89/interactions#3]
Is it possible to have a count modifying on the number of drops?

Also, is it possible to apply the effect only if the replacement is successful?  

This is awesome, thanks so much for making it.

**Comment by tmetcalfe89-zz** [comment]
> Is it possible to have a count modifying on the number of drops?

I'm not sure I understand what you mean. Can you point to an example?

> Also, is it possible to apply the effect only if the replacement is successful?

Probably. Let me tinker with that!

> This is awesome, thanks so much for making it.

Glad you like and are getting some use out of it!

**Comment by jelaw21** [comment]
So like if I apply blaze powder to gravel, instead of dropping one powder,
it can drop two or three.

**Comment by tmetcalfe89-zz** [comment]
Oh wow, I don't have a dropCount! Yeah, I'll get on that.

Also, going to be harder than I wanted to implement only on success. I'd have to have the server tell the client that it succeeded, and I haven't gotten into that yet! Definitely on the to-do list though.

**Comment by jelaw21** [comment]
No issues on that. Just realized, bonemeal doesn't work like that either.

**Comment by tmetcalfe89-zz** [comment]
Just added the dropCount and uploaded as 1.3 (to the right spot this time!). Closing this and adding the particleOnSuccess idea to future ideas.

**Comment by jelaw21** [comment]
Since this is still open, the drops work, but not with the replacement chance.  The drops are 100% regardless of the replacement.  So that kinda goes with particleOnSuccess, drops should happen only on replacement success. Maybe?

**Comment by tmetcalfe89-zz** [comment]
Yeah, leaving it open for the `particleOnSuccess` bit, in case I figure it out or someone with the knowledge to do so does a PR :smile: 

One `dropOnSuccess` coming up!

**Comment by tmetcalfe89-zz** [comment]
As this thread's gotten a bit long and is mostly about the `dropOnSuccess` now, I'm going to move the `particleOnSuccess` over to a separate issue and mark this one as closed.
